markdown: kramdown
remote_theme: fongandrew/hydeout
title: Vedic Astrology
tagline: Birth Chart Predictions from Steve Hora
paginate: 5
author:
  name: Steve Hora
  email: vedicastrology123@gmail.com
  twitter: AstrologyOrbit
description: 'by <a href="https://stevehora.com" target="_blank">Steve Hora</a>.'
url: https://stevehora.com
sass_dir: _scss
