markdown: kramdown
remote_theme: fongandrew/hydeout
title: Vedic Astrology Steve
tagline: Birth Chart Predictions from Steve Hora
paginate: 5
author:
  name: Steve Hora
  email: blah@email.test
  github: username
  twitter: username
  feedburner: feedname
