markdown: kramdown
remote_theme: fongandrew/hydeout
title: Vedic Astrology
tagline: Birth Chart Predictions from Steve Hora
paginate: 5
author:
  name: Steve Hora
  url: https://stevehora.com
  email: vedicastrology123@gmail.com
  twitter: AstrologyOrbit
description: 'by <a href="https://stevehora.com" target="_blank">Steve Hora</a>.'
url: https://stevehora.com
sidebar_home_link:  false
sidebar_blog_link:  'https://stevehora.com/blog/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - github-pages
