markdown: kramdown
theme: mmistakes/minimal-mistakes@4.20.1
title: Vedic Astrology
tagline: Vedic Astrology
author:
  name: Steve Hora
  email: blah@email.test
  github: username
  twitter: username
  feedburner: feedname
