markdown: kramdown
theme: jekyll-theme-slate
title: Vedic Astrology
tagline: Vedic Astrology
author:
  name: Steve Hora
  email: blah@email.test
  github: username
  twitter: username
  feedburner: feedname
