markdown: kramdown
remote_theme: fongandrew/hydeout
title: Vedic Astrology
tagline: Birth Chart Predictions from Steve Hora
paginate: 5
author:
  name: Steve Hora
  email: vedicastrology123@gmail.com
  twitter: @AstrologyOrbit
